In [2]:
import numpy as np
import pandas as pd
pd.set_option('mode.chained_assignment', None)

In [3]:
import pickle


with open('WVS.pkl', 'rb') as f:
    world_values = pickle.load(f)

In [4]:
world_values

,B_COUNTRY,A_WAVE,A_STUDY,B_COUNTRY_ALPHA,C_COW_NUM,C_COW_ALPHA,A_YEAR,D_INTERVIEW,J_INTDATE,K_TIME_START,...,WVS_Polmistrust_PartyVoter,WVS_LR_MedianVoter,WVS_LibCon_MedianVoter,v2psbars,v2psorgs,v2psprbrch,v2psprlnks,v2psplats,v2xnp_client,v2xps_party
0,20,7,2,AND,232,AND,2018,20070001,20180704,18.2,...,62.4342,.,.,.,.,.,.,.,.,.
1,20,7,2,AND,232,AND,2018,20070002,20180714,9.35,...,62.4342,.,.,.,.,.,.,.,.,.
2,20,7,2,AND,232,AND,2018,20070003,20180704,10.15,...,62.4342,.,.,.,.,.,.,.,.,.
3,20,7,2,AND,232,AND,2018,20070004,20180702,17.05,...,.,.,.,.,.,.,.,.,.,.
4,20,7,2,AND,232,AND,2018,20070005,20180708,10.2,...,66.9643,.,.,.,.,.,.,.,.,.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69573,840,7,2,USA,2,USA,2017,840073592,.,.,...,70.6639,5.62,5.7308,2.513,1.449,1.874,1.913,2.364,0.09,0.863
69574,840,7,2,USA,2,USA,2017,840073593,.,.,...,.,.,.,.,.,.,.,.,.,.
69575,840,7,2,USA,2,USA,2017,840073594,.,.,...,70.6639,5.62,5.7308,2.513,1.449,1.874,1.913,2.364,0.09,0.863
69576,840,7,2,USA,2,USA,2017,840073595,.,.,...,70.6639,5.62,5.7308,2.513,1.449,1.874,1.913,2.364,0.09,0.863
69577,840,7,2,USA,2,USA,2017,840073596,.,.,...,.,.,.,.,.,.,.,.,.,.

In [5]:
world_values = world_values[['E_RESPINT', 'F_INTPRIVACY', 'H_SETTLEMENT', 'H_URBRURAL', 'A_YEAR', 'B_COUNTRY_ALPHA', 'Q1', 'Q4', 'Q5', 'Q6', 'Q29', 'Q30', 'Q33', 'Q160', 'Q164']]
world_values

,E_RESPINT,F_INTPRIVACY,H_SETTLEMENT,H_URBRURAL,A_YEAR,B_COUNTRY_ALPHA,Q1,Q4,Q5,Q6,Q29,Q30,Q33,Q160,Q164
0,1,1,1,1,2018,AND,1,3,1,4,3,3,4,7,7
1,1,1,2,1,2018,AND,1,4,1,4,3,3,4,9,1
2,1,1,2,1,2018,AND,1,2,3,3,3,3,4,8,8
3,2,1,2,1,2018,AND,1,4,2,4,4,4,4,5,1
4,2,1,2,1,2018,AND,1,3,1,3,3,3,4,6,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69573,2,1,.,.,2017,USA,1,2,1,1,4,4,4,7,1
69574,1,2,.,.,2017,USA,1,3,2,3,4,3,3,1,5
69575,1,1,.,.,2017,USA,1,4,3,3,4,4,4,1,1
69576,2,1,.,.,2017,USA,1,3,2,4,4,4,4,3,2
69577,.,1,.,.,2017,USA,.,.,.,.,3,3,.,10,10

In [6]:
#interest level of participants in interview
def respint(x):
    if x== 1:
        return 'Very interested'
    elif x== 2:
        return 'Somewhat interested'
    elif x==3:
        return 'Not interested'
    else:
        return pd.NaT
world_values['Interest']= [respint(x) for x in world_values['E_RESPINT']]
world_values = world_values.drop(columns = ['E_RESPINT'])

#privacy level of interview, based on whether there was other people around who could follow the interview
def priv(x):
    if x== 1:
        return 'Very private'
    elif x== 2:
        return 'Not private'
    else:
        return pd.NaT
world_values['Privacy']= [priv(x) for x in world_values['F_INTPRIVACY']]
world_values=world_values.drop(columns = ['F_INTPRIVACY'])

#town size of where the interview took place
# def towns(x):
#     if x== 1:
#         return 'Under 5,000'
#     elif x== 2:
#         return '5000-20000'
#     elif x== 3:
#         return '20000-100000'
#     elif x== 4:
#         '100000-500000'
#     elif x==5:
#         '500000 and more'
#     else:
#         return pd.NaT
# world_values['Town size']= [towns(x) for x in world_values['G_TOWNSIZE2']]
# world_values=world_values.drop(columns = ['G_TOWNSIZE2'])

#Type of settlement where the interview took place
def settype(x):
    if x== 1:
        return 'Capital City'
    elif x== 2:
        return 'Regional center'
    elif x== 3:
        return 'District center'
    elif x== 4:
        'Another city, town (not a regional or district center)'
    elif x==5:
        'Village'
    else:
        return pd.NaT
world_values['Settlement_type']= [settype(x) for x in world_values['H_SETTLEMENT']]
world_values=world_values.drop(columns = ['H_SETTLEMENT'])

#whether the settlement was urband or rural
def ur(x):
    if x== 1:
        return 'Urban'
    elif x== 2:
        return 'Rural'
    else:
        return pd.NaT
world_values['Urban/Rural']= [ur(x) for x in world_values['H_URBRURAL']]
world_values=world_values.drop(columns = ['H_URBRURAL'])

#Duration of the interview
# def dur(x):
#     if type(x) == float:
#         return x
#     else:
#         return pd.NaT
# world_values['Interview Length']= [dur(x) for x in world_values['K_DURATION']]
# world_values=world_values.drop(columns = ['K_DURATION'])

#rename columns of year and country code where no null values exist
world_values=world_values.rename(columns = {'A_YEAR' : "Year"})
world_values=world_values.rename(columns = {'B_COUNTRY_ALPHA' : "Country_Code"})

#Importance of different values
def imp(x):
    if x== 1:
        return 'Very important'
    elif x== 2:
        return 'Rather important'
    elif x== 3:
        return 'Not very important'
    elif x== 4:
        return 'Not at all important'
    else:
        return pd.NaT
world_values['Family_Importance']= [imp(x) for x in world_values['Q1']]
# world_values['Friends Importance']= [imp(x) for x in world_values['Q2']]
# world_values['Leisure Importance']= [imp(x) for x in world_values['Q3']]
world_values['Politics_Importance']= [imp(x) for x in world_values['Q4']]
world_values['Work_Importance']= [imp(x) for x in world_values['Q5']]
world_values['Religion_Importance']= [imp(x) for x in world_values['Q6']]
world_values=world_values.drop(columns = ['Q1', 'Q4', 'Q5', 'Q6'])

#whe depend too much on science and not enough on faith
def tenscale(x):
    if x== 1 or x==2:
        return 'Disagree Strongly'
    elif x== 3 or x==4:
        return 'Disagree'
    elif x== 5 or x==6:
        return 'Neutral'
    elif x== 7 or x==8:
        return 'Agree'
    elif x==9 or x==10:
        return "Agree Strongly"
    else:
        return pd.NaT
world_values['Faith_Over_Science']= [tenscale(x) for x in world_values['Q160']]
world_values = world_values.drop(columns = ['Q160'])

#believe in god yes or no
def god(x):
    if x== 1:
        return 'yes'
    elif x== 2:
        return 'no'
    else:
        return pd.NaT
world_values['Believe']= [god(x) for x in world_values['Q164']]
world_values=world_values.drop(columns = ['Q164'])

#importance of different issues relating to gender
def gen(x):
    if x== 1:
        return 'Agree strongly'
    elif x== 2:
        return 'Agree'
    elif x== 3:
        return 'Neutral'
    elif x== 4:
        return 'Disagree'
    elif x==5:
        return "Disagree Strongly"
    else:
        return pd.NaT
#Men make better politicians than women
world_values['Gender_Politics']= [gen(x) for x in world_values['Q29']]
#university is more important for aboy than a girl men should have more right to a job than women
world_values['Gender_University']= [gen(x) for x in world_values['Q30']]
# we depend too much on science and less on faith
world_values['Gender_Work']= [gen(x) for x in world_values['Q33']]
world_values = world_values.drop(columns = ['Q29', 'Q30', 'Q33'])


#drop null values
world_values = world_values.dropna()

In [7]:
world_values

,Year,Country_Code,Interest,Privacy,Settlement_type,Urban/Rural,Family_Importance,Politics_Importance,Work_Importance,Religion_Importance,Faith_Over_Science,Believe,Gender_Politics,Gender_University,Gender_Work
1,2018,AND,Very interested,Very private,Regional center,Urban,Very important,Not at all important,Very important,Not at all important,Agree Strongly,yes,Neutral,Neutral,Disagree
3,2018,AND,Somewhat interested,Very private,Regional center,Urban,Very important,Not at all important,Rather important,Not at all important,Neutral,yes,Disagree,Disagree,Disagree
12,2018,AND,Very interested,Very private,Regional center,Urban,Very important,Not very important,Rather important,Not at all important,Agree,yes,Disagree,Disagree,Disagree Strongly
16,2018,AND,Very interested,Very private,Regional center,Urban,Very important,Not at all important,Very important,Not at all important,Disagree,yes,Disagree,Disagree,Disagree Strongly
22,2018,AND,Very interested,Very private,Regional center,Urban,Very important,Not at all important,Very important,Not at all important,Agree Strongly,yes,Disagree,Disagree,Disagree Strongly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65536,2018,TUR,Very interested,Very private,Regional center,Urban,Very important,Not very important,Rather important,Rather important,Neutral,no,Agree,Neutral,Agree
65541,2018,TUR,Very interested,Very private,Regional center,Urban,Very important,Not very important,Rather important,Rather important,Neutral,no,Agree,Agree,Agree
65543,2018,TUR,Very interested,Very private,Regional center,Urban,Very important,Not very important,Rather important,Not very important,Neutral,yes,Agree,Neutral,Agree
65545,2018,TUR,Very interested,Very private,Regional center,Urban,Very important,Not very important,Rather important,Not very important,Disagree,yes,Agree,Neutral,Agree strongly
65611,2018,TUR,Very interested,Very private,Regional center,Urban,Rather important,Rather important,Rather important,Rather important,Disagree Strongly,no,Agree strongly,Neutral,Agree strongly

In [12]:
world_values.to_csv(r'C:\Users\5mika\Desktop\polisci3\DSEP-polisci3\World Values Data Cleaning\worldvalues.csv', index = False, header=True)