In [470]:
import pandas as pd
import numpy as np
import seaborn as sns 

import matplotlib.pyplot as plt

In [545]:
conflicts_raw = pd.read_csv('conflicts.csv')  
#conflicts['year'] =  pd.to_datetime(conflicts['year'],format= '%Y')
conflicts_raw.head()

,conflict_id,location,side_a,side_a_id,side_a_2nd,side_b,side_b_id,side_b_2nd,incompatibility,territory_name,...,ep_end,ep_end_date,ep_end_prec,gwno_a,gwno_a_2nd,gwno_b,gwno_b_2nd,gwno_loc,region,version
0,11342,India,Government of India,141,NaN,GNLA,1163,NaN,1,Garoland,...,1,2012-12-21,NaN,750,NaN,NaN,NaN,750,3,20.1
1,11342,India,Government of India,141,NaN,GNLA,1163,NaN,1,Garoland,...,1,2014-11-27,NaN,750,NaN,NaN,NaN,750,3,20.1
2,11343,"Egypt, Israel",Government of Egypt,117,NaN,Government of Israel,121,NaN,1,Suez/Sinai,...,1,1967-06-10,NaN,651,NaN,666,NaN,"651, 666",2,20.1
3,11343,"Egypt, Israel",Government of Egypt,117,NaN,Government of Israel,121,NaN,1,Suez/Sinai,...,0,NaN,NaN,651,NaN,666,NaN,"651, 666",2,20.1
4,11343,"Egypt, Israel",Government of Egypt,117,NaN,Government of Israel,121,NaN,1,Suez/Sinai,...,1,1970-08-07,NaN,651,NaN,666,NaN,"651, 666",2,20.1

In [472]:
conflicts = conflicts_raw.drop(['location','side_a_2nd','side_b_2nd','side_a_id','side_b_id','territory_name',
                                'cumulative_intensity','ep_end_prec','start_prec','start_date2','start_prec2','gwno_a','gwno_loc',
                                'gwno_a_2nd','gwno_b','gwno_b_2nd','region','version'], axis=1)


conflicts= conflicts.sort_values(by=['start_date'])
conflicts.head()

,conflict_id,side_a,side_b,incompatibility,year,intensity_level,type_of_conflict,start_date,ep_end,ep_end_date
194,207,Government of United Kingdom,IZL [Etzel],1,1946,1,1,1939-03-31,1,1946-12-31
270,213,Government of Russia (Soviet Union),UPA,1,1948,2,3,1941-12-31,0,NaN
272,213,Government of Russia (Soviet Union),UPA,1,1950,1,3,1941-12-31,1,1950-12-31
269,213,Government of Russia (Soviet Union),UPA,1,1947,2,3,1941-12-31,0,NaN
268,213,Government of Russia (Soviet Union),UPA,1,1946,2,3,1941-12-31,0,NaN

In [473]:

#pd.set_option('display.max_rows', None)


#for loop for incompatibility, intensity, type, region
incompatible = [] 
for value in conflicts["incompatibility"]: 
    if value == 1: 
        incompatible.append("Territory") 
    elif value == 2: 
        incompatible.append("Government") 
    else: 
        incompatible.append("Government and Territory")
        
conflicts['incompatibility'] = incompatible

#intensity
intense = [] 
for value in conflicts["intensity_level"]: 
    if value == 1: 
        intense.append("Minor")  
    else: 
        intense.append("War")
        
conflicts['intensity_level'] = intense

#type of conflict
types = [] 
for value in conflicts["type_of_conflict"]: 
    if value == 1: 
        types.append("Extrasystemic") 
    elif value == 2: 
        types.append("Interstate") 
    elif value ==3:
        types.append('Internal')
    else: 
        types.append("Internationalized Internal")
        
conflicts['type_of_conflict'] = types

In [474]:
conflicts.set_index('conflict_id')

,side_a,side_b,incompatibility,year,intensity_level,type_of_conflict,start_date,ep_end,ep_end_date
conflict_id,,,,,,,,,
207,Government of United Kingdom,IZL [Etzel],Territory,1946,Minor,Extrasystemic,1939-03-31,1,1946-12-31
213,Government of Russia (Soviet Union),UPA,Territory,1948,War,Internal,1941-12-31,0,NaN
213,Government of Russia (Soviet Union),UPA,Territory,1950,Minor,Internal,1941-12-31,1,1950-12-31
213,Government of Russia (Soviet Union),UPA,Territory,1947,War,Internal,1941-12-31,0,NaN
213,Government of Russia (Soviet Union),UPA,Territory,1946,War,Internal,1941-12-31,0,NaN
...,...,...,...,...,...,...,...,...,...
14197,Government of Somalia,IS,Territory,2019,Minor,Internationalized Internal,2018-02-08,0,NaN
14609,Government of Iran,Government of Israel,Government,2019,Minor,Interstate,2018-02-10,0,NaN
14609,Government of Iran,Government of Israel,Government,2018,Minor,Interstate,2018-02-10,0,NaN
14845,Government of Mozambique,IS,Territory,2019,Minor,Internal,2019-06-04,0,NaN
14935,Government of Ethiopia,Military faction (forces of Asaminew Tsige),Territory,2019,Minor,Internal,2019-06-22,0,NaN

In [475]:
#Clean sides
def clean_country(country):
    return (country
            .replace('Government of ', '')
            .replace(' (Soviet Union)',''))

conflicts['side_a'] = [clean_country(country) for country in conflicts['side_a']]
conflicts['side_b'] = [clean_country(country) for country in conflicts['side_b']]

#conflicts = conflicts.groupby(['side_a','conflict_id']).first()
#conflicts.head()

In [476]:
gdp_raw = pd.read_csv('country_gdp.csv')

In [477]:
pop_raw = pd.read_csv('population.csv')

In [478]:
literacy_raw = pd.read_csv('literacy.csv')
literacy_raw['last_value'] = literacy_raw.ffill(axis=1).iloc[:, -1]

In [479]:
military_raw = pd.read_csv('military.csv')

In [490]:
gini_raw = pd.read_csv('gini.csv')
gini_raw['last_value'] = gini_raw.ffill(axis=1).iloc[:, -1]

In [501]:
cdr_raw = pd.read_csv('cdr.csv')

In [503]:
life_expectancy_raw = pd.read_csv('life_exp.csv')

In [505]:
refugee_raw = pd.read_csv('refugee.csv')

In [499]:
child_mortality_raw = pd.read_csv('child_mortality.csv')

In [481]:
pop_drop = pop_raw[['Country Name']].rename(columns={'Country Name':'side_a'})

In [482]:
#conflicts = conflicts.merge(indicators,on='side_a')
#conflicts = conflicts.groupby(['side_a','conflict_id']).first()

conflicts['year'] = conflicts['year'].apply(str)
conflicts = conflicts.merge(pop_drop,on='side_a')
conflicts

,conflict_id,side_a,side_b,incompatibility,year,intensity_level,type_of_conflict,start_date,ep_end,ep_end_date
0,207,United Kingdom,IZL [Etzel],Territory,1946,Minor,Extrasystemic,1939-03-31,1,1946-12-31
1,229,United Kingdom,CPM,Territory,1956,Minor,Extrasystemic,1948-06-19,0,NaN
2,229,United Kingdom,CPM,Territory,1957,Minor,Extrasystemic,1948-06-19,1,1957-08-31
3,229,United Kingdom,CPM,Territory,1955,Minor,Extrasystemic,1948-06-19,0,NaN
4,229,United Kingdom,CPM,Territory,1954,Minor,Extrasystemic,1948-06-19,0,NaN
...,...,...,...,...,...,...,...,...,...,...
1807,13306,Ukraine,"DPR, LPR",Territory,2016,Minor,Internationalized Internal,2014-09-17,0,NaN
1808,13306,Ukraine,"DPR, LPR",Territory,2017,Minor,Internationalized Internal,2014-09-17,0,NaN
1809,13306,Ukraine,"DPR, LPR",Territory,2018,Minor,Internationalized Internal,2014-09-17,0,NaN
1810,13306,Ukraine,"DPR, LPR",Territory,2019,Minor,Internationalized Internal,2014-09-17,0,NaN
1811,13886,Jordan,IS,Territory,2016,Minor,Internal,2016-03-02,1,2016-12-29

In [494]:
conflicts_1960 = conflicts.loc[conflicts['year'] > '1959']

In [508]:
pops = []
gdp = []
militia = []
gini = []
lit = []
cdr = []
life = []
child = []
refuge = []

conflicts_grouped = conflicts_1960['side_a'].unique()
for country in conflicts_grouped:
    table = conflicts_1960.loc[conflicts_1960['side_a'] == country]
    for year in table['year']:
        pops.append(pop_raw.loc[pop_raw['Country Name'] == country, year].values[0])
        gdp.append(gdp_raw.loc[gdp_raw['Country Name'] == country, year].values[0])
        militia.append(military_raw.loc[military_raw['Country Name'] == country, year].values[0])
        gini.append(gini_raw.loc[gini_raw['Country Name'] == country, year].values[0])
        lit.append(literacy_raw.loc[literacy_raw['Country Name'] == country, year].values[0])
        cdr.append(cdr_raw.loc[cdr_raw['Country Name'] == country, year].values[0])
        life.append(life_expectancy_raw.loc[life_expectancy_raw['Country Name'] == country, year].values[0])
        child.append(child_mortality_raw.loc[child_mortality_raw['Country Name'] == country, year].values[0])
        refuge.append(refugee_raw.loc[refugee_raw['Country Name'] == country, year].values[0])
        

conflicts_1960['GDP'] = gdp
conflicts_1960['Population'] = pops
conflicts_1960['Military Expenditure % GDP'] = militia
conflicts_1960['Gini Index'] = gini
conflicts_1960['Adult Literacy Rate'] = lit
conflicts_1960['Crude Death Rate'] = cdr
conflicts_1960['Child Mortality Rate'] = child
conflicts_1960['Life Expectancy'] = life
conflicts_1960['Refugees from Origin'] = refuge

<ipython-input-508-ab27f7e106ac>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  conflicts_1960['GDP'] = gdp
<ipython-input-508-ab27f7e106ac>:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  conflicts_1960['Population'] = pops
<ipython-input-508-ab27f7e106ac>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  conflicts_1960['Military Expenditure % GDP'] = militia
<ipython-input-508-ab27f7e106ac>:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  conflicts_1960['Gini Index'] = gini
<ipython-input-508-ab27f7e106ac>:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  conflicts_1960['Adult Literacy Rate'] = lit
<ipython-input-508-ab27f7e106ac>:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  conflicts_1960['Crude Death Rate'] = cdr
<ipython-input-508-ab27f7e106ac>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  conflicts_1960['Child Mortality Rate'] = child
<ipython-input-508-ab27f7e106ac>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  conflicts_1960['Life Expectancy'] = life
<ipython-input-508-ab27f7e106ac>:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  conflicts_1960['Refugees from Origin'] = refuge

In [564]:
abrv = pd.read_csv('ucdp-actors.csv')
abrv = abrv[['ActorId','NameData','NameOrig','NameOrigFullEng']]
pd.set_option('display.max_rows', 10)
abrv = abrv.rename(columns = {'NameData':'Side B 1st'})

In [565]:

conflicts_1960 = conflicts_1960.rename(columns = {'side_a': 'Side A', 'side_b': 'Side B', 'conflict_id':'Conflict ID',
                                 'incompatibility':'Incompatibility','type_of_conflict':'Type of Conflict',
                                'year':'Year Observed','intensity_level':'Intensity Level',
                                 'start_date':'Start Date','ep_end':'Ended','ep_end_date':'End Date'})

conflicts_final = conflicts_1960.groupby(['Side A','Conflict ID']).first()
conflicts_final

                                                                       Side B  \
Side A         Conflict ID
Afghanistan    333          Harakat-i Inqilab-i Islami-yi Afghanistan , Hi...
               431                                                     Russia
               13637                                                       IS
               13692                 United Kingdom, United States of America
Algeria        278                                                    Morocco
...                                                                       ...
United Kingdom 273                           North Kalimantan Liberation Army
               286                                                      FLOSY
               315                                                       PIRA
Uruguay        319                                              MLN/Tupamaros
Uzbekistan     415                                                        JIG

                           Incompatibility Year Observed Intensity Level  \
Side A         Conflict ID
Afghanistan    333              Government          1982             War
               431              Government          1979           Minor
               13637             Territory          2016             War
               13692            Government          2001             War
Algeria        278               Territory          1963           Minor
...                                    ...           ...             ...
United Kingdom 273               Territory          1962           Minor
               286               Territory          1964           Minor
               315               Territory          1985           Minor
Uruguay        319              Government          1972           Minor
Uzbekistan     415              Government          2004           Minor

                                      Type of Conflict  Start Date  Ended  \
Side A         Conflict ID
Afghanistan    333          Internationalized Internal  1975-07-02      0
               431                          Interstate  1979-12-27      1
               13637        Internationalized Internal  2015-02-09      0
               13692                        Interstate  2001-10-07      1
Algeria        278                          Interstate  1963-10-08      1
...                                                ...         ...    ...
United Kingdom 273                       Extrasystemic  1962-12-08      1
               286                       Extrasystemic  1964-11-25      0
               315                            Internal  1970-08-11      0
Uruguay        319                            Internal  1970-04-13      1
Uzbekistan     415                            Internal  1999-02-16      1

                              End Date           GDP  Population  \
Side A         Conflict ID
Afghanistan    333                 NaN  1.910135e+10  12882528.0
               431          1979-12-28  3.697940e+09  13411056.0
               13637               NaN  1.936264e+10  35383128.0
               13692        2001-11-13           NaN  21606988.0
Algeria        278          1963-11-04  2.703015e+09  11912803.0
...                                ...           ...         ...
United Kingdom 273          1962-12-31  8.124756e+10  53250000.0
               286          1967-11-29  9.440756e+10  54000000.0
               315          1991-11-26  4.892850e+11  56550268.0
Uruguay        319          1972-12-31  2.189418e+09   2821461.0
Uzbekistan     415          2004-07-30  1.203002e+10  25864350.0

                            Military Expenditure % GDP  Gini Index  \
Side A         Conflict ID
Afghanistan    333                            1.173908         NaN
               431                                 NaN         NaN
               13637                          0.956772         NaN
               13692                               NaN         NaN
Algeria        278                            2.511485         NaN
...                                                ...         ...
United Kingdom 273                            6.210394         NaN
               286                            5.899068         NaN
               315                            4.758479        35.9
Uruguay        319                            2.198068         NaN
Uzbekistan     415                            1.151780        36.1

                            Adult Literacy Rate  Crude Death Rate  \
Side A         Conflict ID
Afghanistan    333                    43.019718         19.865000
               431                    18.157681         21.720000
               13637                  43.019718          6.742000
               13692                        NaN         11.387000
Algeria        278                          NaN         19.176000
...                                         ...               ...
United Kingdom 273                          NaN         11.900000
               286                          NaN         11.300000
               315                          NaN         11.900000
Uruguay        319                          NaN          9.984000
Uzbekistan     415                    98.642578          5.040019

                            Child Mortality Rate  Life Expectancy  \
Side A         Conflict ID
Afghanistan    333                         228.6        44.617000
               431                         247.8        42.585000
               13637                        67.6        63.763000
               13692                       124.6        56.308000
Algeria        278                         243.2        47.509000
...                                          ...              ...
United Kingdom 273                          25.6        70.926829
               286                          24.2        71.624390
               315                          11.4        74.629268
Uruguay        319                          53.3        68.732000
Uzbekistan     415                          50.1        68.135000

                            Refugees from Origin
Side A         Conflict ID
Afghanistan    333                     4488214.0
               431                      500000.0
               13637                   2501447.0
               13692                   3809763.0
Algeria        278                           NaN
...                                          ...
United Kingdom 273                           NaN
               286                           NaN
               315                          88.0
Uruguay        319                           NaN
Uzbekistan     415                        7292.0

[192 rows x 17 columns]